---
- hosts: webservers
  become: true
  tasks: 
    - name: Install packages
      apt: 
        name: "nginx"
        state: "present"
    - name: Start ngnix server
      Service:
        name: ngnix
        state: started
        enabled: true
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/      